SET serveroutput on;

TRUNCATE TABLE src_employees;
TRUNCATE TABLE dim_employees;

/*
    What is SCD2:
    SCD2 allows you to track historical changes in dimension (aka history) records.
    Allows programmers to maintain and view the full history of changes.
    
    *Those descriptions are made based on my implementation and serve as an example*
    
    1. SCD2 with Triggers
        - create a BEFORE UPDATE trigger on the source table which will record into the history table the new values
        - updates the current row and marks it as EXPIRED
        Advantages:
        - easy to implement 
        - process is automatic because of the triggers
        - works well with OLTP logic and systems
        Cons:
        - performance decreases - runs on every change
        - complex to maintain as logic grows
        - prone to errors in big applications
    2. SCD2 with CDC (Change Data Capture)
        - the DB captures change logs using internal mechanisms( like logs, flashbacks, implicit triggers)
        - ETL tools mark the changes and apply the logic downstream
        Advantages:
        - near real-time actions
        - lightweight for the system
        - good for streaming into data lakes ( Snowflake, BigQuery...)
        Cons:
        - complex setup and implementation
        - may require extra licenses and tools
        - dev still needs to apply SCD2 logic separatly downstream
    3. SCD2 with ETL (Extract, Transform, Load model)
        - can run on schedule
        - pull full or partial data from sources
        Advantages:
        - best approach for data warehouse or reporting
        - easy to control logic with SQL or related tools (ODI, Talend..)
        - very easy to scale
        Cons:
        - no real-time
        - requires good design for large volumes and transactions( partitioning, bulk loads, etc..)
        - needs data gouveranance to avoid duplicates
        
    Summary:
        USE WITH TRIGGERS WHEN -> work on small oltp app trakers with few changes
        USE WITH CDC WHEN -> work with real-time sync or Kafka/DL pipelines
        USE WITH ETL ->  work with batch-based historycal tracking for BI apps 
*/

/*
    Step 1: Base setup -> common source stable and history table for all examples
        - source table : where the updates are made;
        - dimension/history table : where the history is stored;
        - inserts into source table
*/

-- source table table where the updates happen.
-- * we will simulate changes on this table (salary changes, department transfers...)
CREATE TABLE src_employees (
    emp_id        NUMBER PRIMARY KEY,
    full_name     VARCHAR2(100),
    department    VARCHAR2(100),
    salary        NUMBER,
    last_updated  DATE
);


-- history/dimension table that will store the changes, the OLD versions of the employee.
-- * NEW ROW MEANS NEW VERSION
CREATE TABLE dim_employees (
    surrogate_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    emp_id         NUMBER,
    full_name      VARCHAR2(100),
    department     VARCHAR2(100),
    salary         NUMBER,
    start_date     DATE,
    end_date       DATE,
    current_flag   CHAR(1)  -- we will use Y for active, N for expired
);

--inserts
BEGIN
    INSERT INTO src_employees (emp_id, full_name, department, salary, last_updated)
    VALUES (101, 'Alice Smith', 'HR', 3000, SYSDATE);
    INSERT INTO src_employees (emp_id, full_name, department, salary, last_updated)
    VALUES (102, 'Bob Johnson', 'IT', 4000, SYSDATE);
    INSERT INTO src_employees (emp_id, full_name, department, salary, last_updated)
    VALUES (103, 'Maria Elena', 'MARKETING', 5000, SYSDATE);
    INSERT INTO src_employees (emp_id, full_name, department, salary, last_updated)
    VALUES (104, 'Bob Johnson', 'SALES', 6000, SYSDATE);
    COMMIT;
END;

-- check if inserts are commited
SELECT * FROM src_employees;    -- HERE YOU CAN SEE THE INSERTED DATA
SELECT * FROM dim_employees; -- EMPTY FOR NOW

-- Load current employees into history table
BEGIN
    INSERT INTO dim_employees (
        emp_id, full_name, department, salary,
        start_date, end_date, current_flag)
    SELECT 
        emp_id, full_name, department, salary,SYSDATE, NULL, 'Y'
    FROM src_employees;
    COMMIT;
END;

SELECT * FROM dim_employees; -- Populated

/*
    IMPLEMENTATION OF THE SCD WITH TRIGGERS
        -I WILL CREATE A BEFORE UPDATE TRIGGER ON THE SOURCE TABLE
            -> checks if any tracked columns are changing
            -> if column changes, expires the current record of that employee and inserts a new version
*/
 -- CREATE TRIGGER ---
CREATE OR REPLACE TRIGGER trg_scd2_employees
BEFORE UPDATE ON src_employees          -- before update trigger on source table
FOR EACH ROW
DECLARE
    v_changed BOOLEAN := FALSE;
BEGIN
    -- Step 1: Detect change in tracked columns (on deparmtent, salary and name)
    IF :NEW.department != :OLD.department OR :NEW.salary != :OLD.salary OR :NEW.full_name != :OLD.full_name THEN
       v_changed := TRUE;   --flag that activates when changes are made
    END IF;

    IF v_changed THEN
        -- Step 2: Expire current record in dim_employees
        UPDATE dim_employees
        SET end_date = SYSDATE,
            current_flag = 'N'
        WHERE emp_id = :OLD.emp_id
          AND current_flag = 'Y';

        -- Step 3: Insert new version into dim_employees
        INSERT INTO dim_employees (emp_id, full_name, department, salary,start_date, end_date, current_flag)
        VALUES (:NEW.emp_id, :NEW.full_name, :NEW.department, :NEW.salary,SYSDATE, NULL, 'Y');
    END IF;
END;
/

/*
    Testing area
    Here we will test the trigger
*/
BEGIN
    UPDATE src_employees
    SET salary = 3500
    WHERE emp_id = 101;
    COMMIT;
END;

-- this will display all the history for the employee with id 101
-- One entry will have the flagg N, meaning it is the past value (you can see the end date too being != null )
SELECT * FROM dim_employees
WHERE emp_id = 101
ORDER BY start_date;




/*
    IMPLEMENTATION OF THE SCD WITH ETL SIMULATION
        -FOR EACH RECORD IN THE SOURCE TABLE, THE ETL PROCESS SHOULD:
            -> checks if the employee exists
            -> if new -> insert a new version
            -> if changed (Eg. salary, department) expire old row, insert a new one
*/

-- ============================
-- ========== TEST ============

-- run first the TEST AREA
-- then run each step in order, and finish with the select statement for displaying

--ADD A NEW EMPLOYEE
BEGIN
    INSERT INTO src_employees
    (emp_id, full_name, department, salary, last_updated)
    VALUES (105, 'Mihai Ivan', 'Finance', 4200, SYSDATE);
    commit;
END;
--UPDATE an employee
BEGIN
    UPDATE src_employees
    SET department = 'Marketing'
    WHERE emp_id = 104;
    commit;
END;

-- ============================
-- ========== STEP 1 ============
--Detect changed records by comparing the source table with the dimension records on the flag
-- We will store only the changed employees in the view

CREATE OR REPLACE VIEW view_scd2_changed_employees AS
SELECT s.*
FROM src_employees s
JOIN dim_employees d
  ON s.emp_id = d.emp_id
WHERE d.current_flag = 'Y'
  AND (
       s.full_name   <> d.full_name OR
       s.department  <> d.department OR
       s.salary      <> d.salary
      );
      
CREATE GLOBAL TEMPORARY TABLE tmp_changed_employees (
    emp_id        NUMBER,
    full_name     VARCHAR2(100),
    department    VARCHAR2(100),
    salary        NUMBER
) ON COMMIT PRESERVE ROWS;

-- Step: Insert view result into temp table
INSERT INTO tmp_changed_employees
SELECT emp_id, full_name, department, salary
FROM view_scd2_changed_employees;

SELECT * FROM view_scd2_changed_employees;
SELECT * FROM src_employees;
SELECT * FROM dim_employees;
-- ============================
-- ========== STEP 2 ============
-- we will update the dimension table because we need to expire the current records if changes happen
BEGIN
    UPDATE dim_employees d
    SET end_date = SYSDATE, current_flag = 'N'
    WHERE d.current_flag = 'Y'
    AND EXISTS (
        SELECT 1 FROM tmp_changed_employees t
        WHERE t.emp_id = d.emp_id
    );
      COMMIT;
END;

-- ============================
-- ========== STEP 3 ============
--insert new versions into dim_employees
BEGIN
    INSERT INTO dim_employees (emp_id, full_name, department, salary,start_date, end_date, current_flag)
    SELECT s.emp_id, s.full_name, s.department, s.salary,SYSDATE, NULL, 'Y'
    FROM tmp_changed_employees s;
    COMMIT;
END;
SELECT * FROM view_scd2_changed_employees;

-- ============================
-- ========== STEP 4 ============
--handle new employees -> inserts employees that don't exist yet in dimension table
BEGIN
    INSERT INTO dim_employees (emp_id, full_name, department, salary,start_date, end_date, current_flag)
    SELECT s.emp_id, s.full_name, s.department, s.salary,SYSDATE, NULL, 'Y'
    FROM src_employees s
    WHERE NOT EXISTS (
        SELECT 1 FROM dim_employees d
        WHERE d.emp_id = s.emp_id
    );
    COMMIT;
END;

--Check result
SELECT * FROM dim_employees ORDER BY emp_id, start_date;
--You should see: Employee 105 as a new insert | Employee 104 with old expired version, plus a new version inserted



