---
all:
  vars:
    group: ansible
  children:
    tomcat:
      children:
        webapp:
          hosts:
            web1:
              ansible_host: 
              host_var1: value
            web2:
              ansible_host: 
              host_var2: value
          vars:
            httpd_version: 2.4.37
    database:
      hosts:
        db1:
          ansible_host: 
      vars:
        mysql_url_rpm: https://dev.mysql.com/get/mysql80-community-release-el8-3.noarch.rpm
        mysql_package_name: mysql-server



